uploads = []

[[generated]]
id = "Etd9q3BJIAVi-iQn_yFBN"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "QSapYcQjXGMkxm_QClpGM"
uri = "file://artifacts/mobile/assets/images/splash.png"
type = "image"
title = "generated_image"

[[outputs]]
id = "97SYLfRM68icPv8OoAxRv"
uri = "file://artifacts/mobile/README.md"
type = "text"
title = "GrimX - Coding IDE README"
